repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0 
    hooks:
      - id: trailing-whitespace 
      - id: end-of-file-fixer    
      - id: check-merge-conflict
      - id: check-docstring-first

  - repo: https://github.com/psf/black
    rev: '23.9.1'
    hooks:
      - id: black
        files: \.py$
        args: [--line-length=100]

  - repo: https://github.com/PyCQA/isort
    rev: '5.12.0'
    hooks:
      - id: isort
        args: [--profile=black, --line-length=100]
